name: Code Checks
on:
  pull_request:
  merge_group:

jobs:
  Check_Linting:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: true
      - name: Lint
        run: pnpm run lint