name: Code Checks
on:
  pull_request:
  merge_group:

jobs:
  Check_Linting:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - name: Enable corepack
        run: npm i -g corepack@latest && corepack enable
      - name: Install dependencies
        run: corepack pnpm install
      - name: Lint
        run: pnpm run lint
