name: Code Checks
on:
  pull_request:
  merge_group:

jobs:
  Check_Linting:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          run_install: true
          cache: true
          standalone: true
      - name: Lint
        run: pnpm run lint
        continue-on-error: true
      - run: git status
      - uses: tj-actions/verify-changed-files@v20
        with:
          fail-if-changed: true
          fail-message: 'Looks like there may be auto-fixable linting issues. Run "pnpm lint" to fix them.'
      - name: Format
        run: pnpm run format
      - run: git status
      - uses: tj-actions/verify-changed-files@v20
        with:
          fail-if-changed: true
          fail-message: 'Looks like there may be formatting issues. Run "pnpm format" to fix them.'
      - name: Lint (fail on errors)
        run: pnpm run lint
