name: Claude Code

on:
  workflow_call:
    secrets:
      SECRETS_JSON:
        required: false

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - name: Load .env file
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ secrets.SECRETS_JSON }}

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ env.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

          claude_args: >-
            --dangerously-skip-permissions
            --allowedTools "mcp__github__*"
