name: Code Checks

on:
  workflow_call:
    secrets:
      SECRETS_JSON:
        required: false
    inputs:
      runOnGithubActions:
        required: true
        type: boolean

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

jobs:
  formatting:
    runs-on: ${{ inputs.runOnGithubActions && 'ubuntu-latest' || 'blacksmith-16vcpu-ubuntu-2404-arm' }}
    steps:
      # begin installation
      - name: Load .env file
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ secrets.SECRETS_JSON }}
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true
      - uses: pnpm/action-setup@v4
        with:
          cache: true
      - name: Mount node_modules
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-node-modules
          path: ./node_modules
      - name: Mount next cache
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-next-cache
          path: ./.next
      - name: Mount wireit cache
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-wireit-cache
          path: ./.wireit
      - name: Install dependencies
        run: pnpm install
        # end installation

      # lint
      - run: pnpm run lint
        continue-on-error: true
      - run: git status
      - uses: tj-actions/verify-changed-files@v20
        with:
          fail-if-changed: true
          fail-message: 'Looks like there may be auto-fixable linting issues. Run "pnpm lint" to fix them.'

      # format
      - run: pnpm run format
      - run: git status
      - uses: tj-actions/verify-changed-files@v20
        with:
          fail-if-changed: true
          fail-message: 'Looks like there may be formatting issues. Run "pnpm format" to fix them.'

  build:
    runs-on: ${{ inputs.runOnGithubActions && 'ubuntu-latest' || 'blacksmith-16vcpu-ubuntu-2404-arm' }}
    steps:
      # begin installation
      - name: Load .env file
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ secrets.SECRETS_JSON }}
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          lfs: true
      - uses: pnpm/action-setup@v4
        with:
          cache: true
      - name: Mount node_modules
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-node-modules
          path: ./node_modules
      - name: Mount next cache
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-next-cache
          path: ./.next
      - name: Mount wireit cache
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ github.repository }}-wireit-cache
          path: ./.wireit
      - name: Install dependencies
        run: pnpm install
        # end installation

      # running a build will also check types
      - run: pnpm run build
